[package]
name = "h11types"
version = "0.0.1"
edition = "2021"
description = "h11spec core types"
homepage = "https://github.com/yaws-rs/h11spec"
keywords = ["io", "uring", "epoll", "async"]
license = "Apache-2.0/MIT"
readme = "README.md"
repository = "https://github.com/yaws-rs/h11spec"
categories = ["science"]

[dependencies]
#logos = { version = "0.14", default-features = false, features = ["export_derive"] }
logos = { version = "0.16", default-features = false, features = ["export_derive"] }
yuri = { version = "0.1" }
# maciejhirsz/logos/issues/568
#quoted-values = { version = "0.1", features = ["decode"] }

[dev-dependencies]
insta = { version = "1.47" }
rstest = { version = "0.26" }
criterion = { version = "0.5" }
httparse = { version = "1.0" }

[features]
default = []
alloc = []
ptr = []
static = []
std = []

[package.metadata.docs.rs]
features = [""]

[[bench]]
name = "bencher"
required-features = []
harness = false

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(h11types_status_parser, values("httparse"))',
  'cfg(h11types_header_parser, values("httparse"))',
  'cfg(h11types_kv, values("combined"))',
] }